# Generated by Django 3.1 on 2022-10-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221003_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('certificationId', models.CharField(max_length=64, null=True)),
                ('issuingAthority', models.CharField(max_length=64)),
                ('issueDate', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('work', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='person',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='person',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='person',
            new_name='applicant',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='person',
            new_name='applicant',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.AddField(
            model_name='resume',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
        migrations.DeleteModel(
            name='Certifications',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
