# Generated by Django 3.1 on 2022-10-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221003_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curriculumVitae',
            field=models.FileField(null=True, upload_to='curriculumVitaes'),
        ),
    ]
