# Generated by Django 3.1 on 2022-10-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_curriculumvitae'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='digreeName',
            field=models.CharField(default='Batchelors', max_length=64),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieveements', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.profile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.profile'),
        ),
    ]
