# Generated by Django 3.1 on 2022-10-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221009_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='digreeName',
            new_name='degreeName',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='search engine', max_length=64),
            preserve_default=False,
        ),
    ]
